### ISSUE TITLE
CSS中央寄せスライドレビュー

### ISSUE THREAD

**Issue by kubosho** [yoshiko-pg/slides#1]
中央寄せについて全てのやり方は知ってましたが、改めて勉強になりました。
自分はtransform派でした。
では、以下レビューです。

---
- 6ページ
  - 中央寄せの方法を、箇条書きでいくつか書いておくといいかもしれません（flexbox, TRBLメソッドなど）
  - この後話す内容を予測させる意図もあります
- 16ページ
  - 「widthとheightの値がmarginの値に影響する」=>「width・heightの値とmarginの値が依存する」
  - このほうが分かりやすそう
- 21ページ
  - 「transformの値は要別計算」=>「transformの値は別に計算が必要」
  - 「要別計算」と漢字が集まりすぎている感じがしました
- 24ページ
  - CSS2.1の日本語訳を参照していますが、CSS2.2のほうを参照したほうがいいです
  - http://momdo.github.io/css2/visudet.html#abs-non-replaced-width
  - 訳に誤りがあった場合は、CSS2.2のほうだけ修正するはず
- 25ページ
  - top, bottom, right, leftに0を指定していたのは、値を初期値のauto以外の何かにする必要があったということです。（なので対になる値が等しければ0以外でもOK）
  - 上記の文を「なぜtop, bottom, right, leftを0にするの？」みたいにあらかじめ書いておいたほうがいいと思います（結論を先に書くメソッド）
  - もしくは口頭で「なぜtop, bottom, right, leftを0にするか理由を見てみましょう」と言うのもありかもしれません
- 30ページ
  - 突然`.between`というセレクタが出てきて混乱しました
  - 10ページのHTMLには無かったので…
- 34ページ
  - デメリットの画像があまり辛そうに見えない（普通に使えるよう見える）
  - flexboxは仕様が2回大きく変わって、ブラウザーの実装もbox, flexbox, flexで分かれているということも書いておくといいかも？
- 37ページ
  - Public domainな画像でなければ、出典を書いておいたほうがいいと思います

**Comment by yoshiko-pg** [comment]
@kubosho ありがとうございます！反映しました( ´ ▽ ` )
助かりましたー！
最後の画像は（最初の画像も）著作権明記不要のフリー素材のものなので、そのままにしてあります！
